drop table if exists bookmarks;

create table bookmarks(
    id INTEGER primary key generated by default as identity,
    b_name text not null,
    b_url text not null,
    b_description text
);

insert into bookmarks (b_name, b_url, b_description)
values 
    ('Google', 'google.com', 'google'),
    ('Medium', 'medium.com', 'tech blogs etc.'),
    ('Thinkful', 'thinkful.com', 'coding bootcamp website'),
    ('Sweetwater', 'sweetwater.com', 'musical instrument store'),
    ('PostgreSQL', 'https://www.postgresql.org/', 'postgresql documentation'),
    ('Dropbox', 'dropbox.com', 'cloud file storage'),
    ('Spotify', 'spotify.com', 'online music player'),
    ('YouTube', 'youtube.com', 'online video player and library'),
    ('Gmail', 'gmail.com', 'email account'),
    ('Outlook', 'outlook.com', 'email account - ms');